apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mydatabaseapp
spec:
  components:
    - name: cloud-db
      type: cloud-database
      properties:
        # Your cloud database properties here
    - name: backend
      type: webservice
      properties:
        image: "my-backend-image"
        port: 80
      traits:
        - type: bindings
          properties:
            database: cloud-db
