apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mywebapp
spec:
  components:
    - name: backend
      type: webservice
      properties:
        image: "nginx"
        port: 80
      traits:
        - type: ingress
          properties:
            domain: example.com
            http:
              "/": 80
